#!/usr/bin/env node
/**
 * Reads completion-source.json and writes:
 * - ../../Editor/editorfe/src/completionData.js
 * - ../../docs/jswidget.d.ts
 * - ../../docs-site/public/editor/jswidget.d.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "../..");
const src = JSON.parse(readFileSync(join(__dirname, "completion-source.json"), "utf8"));

const editorOut = join(root, "Editor/editorfe/src/completionData.js");
const docsDts = join(root, "docs/jswidget.d.ts");
const siteDtsDir = join(root, "docs-site/public/editor");
const siteDts = join(siteDtsDir, "jswidget.d.ts");

function escapeJsString(s) {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\n/g, "\\n");
}

function buildCompletionDataJs() {
  const lines = [];
  lines.push("/** Auto-generated by Tools/completion-gen/generate.mjs — do not edit by hand */");
  lines.push("");
  lines.push("export const jsxTags = " + JSON.stringify(src.jsxTags, null, 2) + ";");
  lines.push("");
  lines.push("export const commonAttributes = " + JSON.stringify(src.commonAttributes, null, 2) + ";");
  lines.push("");
  lines.push("export const tagAttributes = " + JSON.stringify(src.tagAttributes, null, 2) + ";");
  lines.push("");
  lines.push("export const apis = " + JSON.stringify(src.apis, null, 2) + ";");
  lines.push("");
  return lines.join("\n");
}

function unionStringLiterals(values) {
  if (!values || !values.length) return "string";
  return values.map((v) => JSON.stringify(v)).join(" | ");
}

function jsxTagPropertyKey(tag) {
  return /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(tag) ? tag : JSON.stringify(tag);
}

const PADDING_TYPE =
  "number | { horizontal?: number; vertical?: number; top?: number; bottom?: number; leading?: number; trailing?: number; left?: number; right?: number }";

const FONT_TYPE = [
  'JSWidgetFontName',
  "number",
  "{ name?: JSWidgetFontName; weight?: JSWidgetFontWeight; design?: JSWidgetFontDesign; size?: number; custom?: string }",
].join(" | ");

const FONT_NAME_LITERALS = [
  "largeTitle", "title", "title2", "title3", "headline", "subheadline",
  "body", "callout", "footnote", "caption", "caption2",
];

const FONT_WEIGHT_LITERALS = [
  "ultraLight", "thin", "light", "regular", "medium",
  "semibold", "bold", "heavy", "black",
];

const FONT_DESIGN_LITERALS = ["monospaced", "rounded", "serif", "default"];

function attributeTypeDts(attr) {
  if (attr.name === "size" && !attr.values) {
    return 'string | { width?: number | "fill"; height?: number | "fill"; minWidth?: number; maxWidth?: number | "fill"; minHeight?: number; maxHeight?: number | "fill" }';
  }
  if (attr.name === "font") return "JSWidgetFont";
  if (attr.values?.length) return unionStringLiterals(attr.values);
  if (attr.name === "padding") return "JSWidgetPadding";
  if (attr.name === "color") return "string";
  if (
    [
      "cornerRadius",
      "opacity",
      "rotationEffect",
      "scaleEffect",
      "blur",
      "thickness",
      "length",
      "lineLimit",
      "minimumScaleFactor",
      "radius",
      "value",
      "min",
      "max",
    ].includes(attr.name)
  ) {
    return "number";
  }
  return "string | number | boolean";
}

function formatAttributeLine(attr) {
  const comment = attr.info ? `      /** ${attr.info} */\n` : "";
  return `${comment}      ${attr.name}?: ${attributeTypeDts(attr)};`;
}

function buildDts() {
  const parts = [];
  parts.push("/** Auto-generated by Tools/completion-gen/generate.mjs */");
  parts.push("");
  parts.push("type HttpParams = { headers?: Record<string, string>; body?: unknown; timeoutInterval?: number };");
  parts.push("type JSWidgetConsole = { log(...args: unknown[]): void; warn(...args: unknown[]): void; error(...args: unknown[]): void };");
  parts.push("type JSWidgetPadding = " + PADDING_TYPE + ";");
  parts.push("type JSWidgetFontName = " + unionStringLiterals(FONT_NAME_LITERALS) + ";");
  parts.push("type JSWidgetFontWeight = " + unionStringLiterals(FONT_WEIGHT_LITERALS) + ";");
  parts.push("type JSWidgetFontDesign = " + unionStringLiterals(FONT_DESIGN_LITERALS) + ";");
  parts.push("type JSWidgetFont = " + FONT_TYPE + ";");
  parts.push(
    'type JSWidgetSize = "small" | "medium" | "large" | "extraLarge" | "accessoryInline" | "accessoryCircular" | "accessoryRectangular" | "live-activity" | "dynamic-island" | "function";'
  );
  parts.push("");
  parts.push("declare const $http: {");
  parts.push("  get(url: string, params?: HttpParams): Promise<string>;");
  parts.push("  post(url: string, params?: HttpParams): Promise<string>;");
  parts.push("  put(url: string, params?: HttpParams): Promise<string>;");
  parts.push("  patch(url: string, params?: HttpParams): Promise<string>;");
  parts.push("  delete(url: string, params?: HttpParams): Promise<string>;");
  parts.push("};");
  parts.push("");
  parts.push("declare function $fetch(url: string, params?: HttpParams): Promise<string>;");
  parts.push("declare function fetch(url: string, params?: HttpParams): Promise<string>;");
  parts.push("");
  parts.push("declare const $console: JSWidgetConsole;");
  parts.push("/** Widget script console (not DOM console). Requires editor lib without DOM. */");
  parts.push("declare const console: JSWidgetConsole;");
  parts.push("");
  parts.push("declare const $device: {");
  parts.push("  name(): string;");
  parts.push("  model(): string;");
  parts.push("  systemVersion(): string;");
  parts.push("  batteryLevel(): number;");
  parts.push("  isCharging(): boolean;");
  parts.push("};");
  parts.push("");
  parts.push("declare const $file: { read(path: string): Promise<string>; write(path: string, content: string): Promise<boolean>; list(path: string): Promise<string[]> };");
  parts.push("declare const $system: Record<string, unknown>;");
  parts.push("declare const $health: Record<string, unknown>;");
  parts.push("declare const $location: Record<string, unknown>;");
  parts.push("declare const $storage: {");
  parts.push("  getString(key: string): string;");
  parts.push("  setString(key: string, value: string): boolean;");
  parts.push("  getJSON(key: string): Record<string, unknown>;");
  parts.push("  setJSON(key: string, value: Record<string, unknown>): boolean;");
  parts.push("  remove(key: string): boolean;");
  parts.push("  keys(): string[];");
  parts.push("  clear(): boolean;");
  parts.push("};");
  parts.push('declare function $getenv(key: "widget-size"): JSWidgetSize | "";');
  parts.push('declare function $getenv(key: "widget-param" | "script-dir"): string;');
  parts.push("declare function $getenv(key: string): string;");
  parts.push("declare function $import(path: string): Promise<unknown>;");
  parts.push("declare function $render(element: unknown): void;");
  parts.push("declare const $dynamic_island: Record<string, unknown>;");
  parts.push("declare const $element: { createElement(tag: unknown, props?: unknown, ...children: unknown[]): unknown };");
  parts.push("declare const $component: Record<string, unknown>;");
  parts.push("declare const $error: Record<string, unknown>;");
  parts.push("");
  parts.push("declare namespace JSWidget {");
  parts.push("  function createElement(tag: unknown, props?: unknown, ...children: unknown[]): unknown;");
  parts.push("  const Fragment: string;");
  parts.push("  namespace JSX {");
  parts.push("    interface IntrinsicElements {");

  for (const tag of src.jsxTags) {
    const tagAttrs = src.tagAttributes[tag] || [];
    const tagNames = new Set(tagAttrs.map((a) => a.name));
    const commonLines = (src.commonAttributes || [])
      .filter((a) => !tagNames.has(a.name))
      .map(formatAttributeLine)
      .join("\n");
    const tagLines = tagAttrs.map(formatAttributeLine).join("\n");
    const body = [commonLines, tagLines].filter(Boolean).join("\n");
    parts.push(`      /** ${tag} */\n      ${jsxTagPropertyKey(tag)}: {\n${body}\n      };`);
  }

  parts.push("    }");
  parts.push("  }");
  parts.push("}");
  parts.push("");
  return parts.join("\n");
}

writeFileSync(editorOut, buildCompletionDataJs(), "utf8");
writeFileSync(docsDts, buildDts(), "utf8");
mkdirSync(siteDtsDir, { recursive: true });
writeFileSync(siteDts, buildDts(), "utf8");
console.log("Wrote:", editorOut, docsDts, siteDts);
