#!/usr/bin/env node
/**
 * Reads completion-source.json and writes:
 * - ../../Editor/editorfe/src/completionData.js
 * - ../../docs/jswidget.d.ts
 * - ../../docs-site/public/editor/jswidget.d.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "../..");
const src = JSON.parse(readFileSync(join(__dirname, "completion-source.json"), "utf8"));

const editorOut = join(root, "Editor/editorfe/src/completionData.js");
const docsDts = join(root, "docs/jswidget.d.ts");
const siteDtsDir = join(root, "docs-site/public/editor");
const siteDts = join(siteDtsDir, "jswidget.d.ts");

function escapeJsString(s) {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\n/g, "\\n");
}

function buildCompletionDataJs() {
  const lines = [];
  lines.push("/** Auto-generated by Tools/completion-gen/generate.mjs — do not edit by hand */");
  lines.push("");
  lines.push("export const jsxTags = " + JSON.stringify(src.jsxTags, null, 2) + ";");
  lines.push("");
  lines.push("export const commonAttributes = " + JSON.stringify(src.commonAttributes, null, 2) + ";");
  lines.push("");
  lines.push("export const tagAttributes = " + JSON.stringify(src.tagAttributes, null, 2) + ";");
  lines.push("");
  lines.push("export const apis = " + JSON.stringify(src.apis, null, 2) + ";");
  lines.push("");
  return lines.join("\n");
}

function unionStringLiterals(values) {
  if (!values || !values.length) return "string";
  return values.map((v) => JSON.stringify(v)).join(" | ");
}

function buildDts() {
  const parts = [];
  parts.push("/** Auto-generated by Tools/completion-gen/generate.mjs */");
  parts.push("");
  parts.push("type HttpParams = { headers?: Record<string, string>; body?: unknown; timeoutInterval?: number };");
  parts.push("");
  parts.push("declare const $http: {");
  parts.push("  get(url: string, params?: HttpParams): Promise<string>;");
  parts.push("  post(url: string, params?: HttpParams): Promise<string>;");
  parts.push("  put(url: string, params?: HttpParams): Promise<string>;");
  parts.push("  patch(url: string, params?: HttpParams): Promise<string>;");
  parts.push("  delete(url: string, params?: HttpParams): Promise<string>;");
  parts.push("};");
  parts.push("");
  parts.push("declare function $fetch(url: string, params?: HttpParams): Promise<string>;");
  parts.push("declare function fetch(url: string, params?: HttpParams): Promise<string>;");
  parts.push("");
  parts.push("declare const $console: { log(...args: unknown[]): void; warn(...args: unknown[]): void; error(...args: unknown[]): void };");
  parts.push("declare const console: typeof $console;");
  parts.push("");
  parts.push("declare const $device: {");
  parts.push("  name(): string;");
  parts.push("  model(): string;");
  parts.push("  systemVersion(): string;");
  parts.push("  batteryLevel(): number;");
  parts.push("  isCharging(): boolean;");
  parts.push("};");
  parts.push("");
  parts.push("declare const $file: { read(path: string): Promise<string>; write(path: string, content: string): Promise<boolean>; list(path: string): Promise<string[]> };");
  parts.push("declare const $system: Record<string, unknown>;");
  parts.push("declare const $health: Record<string, unknown>;");
  parts.push("declare const $location: Record<string, unknown>;");
  parts.push("declare const $storage: { get(key: string): Promise<string | null>; set(key: string, value: string): Promise<void>; remove(key: string): Promise<void>; clear(): Promise<void> };");
  parts.push("declare const $getenv: { get(key: string): string | undefined };");
  parts.push("declare function $import(path: string): Promise<unknown>;");
  parts.push("declare function $render(element: unknown): void;");
  parts.push("declare const $dynamic_island: Record<string, unknown>;");
  parts.push("declare const $element: { createElement(tag: unknown, props?: unknown, ...children: unknown[]): unknown };");
  parts.push("declare const $component: Record<string, unknown>;");
  parts.push("declare const $error: Record<string, unknown>;");
  parts.push("");
  parts.push("declare namespace JSWidget {");
  parts.push("  function createElement(tag: unknown, props?: unknown, ...children: unknown[]): unknown;");
  parts.push("  const Fragment: string;");
  parts.push("  namespace JSX {");
  parts.push("    interface IntrinsicElements {");

  const common = [
    "size?: string | { width?: number | \"fill\"; height?: number | \"fill\"; minWidth?: number; maxWidth?: number | \"fill\"; minHeight?: number; maxHeight?: number | \"fill\" };",
    "justify?: \"start\" | \"center\" | \"end\";",
    "align?: \"start\" | \"center\" | \"end\";",
    "padding?: number | string;",
    "backgroundColor?: string;",
    "foregroundColor?: string;",
    "cornerRadius?: number;",
    "opacity?: number;",
    "rotationEffect?: number;",
    "scaleEffect?: number;",
    "offset?: string;",
    "shadow?: string;",
    "blur?: number;",
    "animation?: string;",
  ].join("\n      ");

  for (const tag of src.jsxTags) {
    const attrs = src.tagAttributes[tag] || [];
    const props = attrs
      .map((a) => {
        const opt = a.values ? `${a.name}?: ${unionStringLiterals(a.values)}` : `${a.name}?: string | number | boolean`;
        return `      /** ${a.info || ""} */\n      ${opt};`;
      })
      .join("\n");
    parts.push(`      /** ${tag} */\n      ${tag}: {\n      ${common}\n${props}\n      };`);
  }

  parts.push("    }");
  parts.push("  }");
  parts.push("}");
  parts.push("");
  return parts.join("\n");
}

writeFileSync(editorOut, buildCompletionDataJs(), "utf8");
writeFileSync(docsDts, buildDts(), "utf8");
mkdirSync(siteDtsDir, { recursive: true });
writeFileSync(siteDts, buildDts(), "utf8");
console.log("Wrote:", editorOut, docsDts, siteDts);
