/** Auto-generated by Tools/completion-gen/generate.mjs */

type HttpParams = { headers?: Record<string, string>; body?: unknown; timeoutInterval?: number };

declare const $http: {
  get(url: string, params?: HttpParams): Promise<string>;
  post(url: string, params?: HttpParams): Promise<string>;
  put(url: string, params?: HttpParams): Promise<string>;
  patch(url: string, params?: HttpParams): Promise<string>;
  delete(url: string, params?: HttpParams): Promise<string>;
};

declare function $fetch(url: string, params?: HttpParams): Promise<string>;
declare function fetch(url: string, params?: HttpParams): Promise<string>;

declare const $console: { log(...args: unknown[]): void; warn(...args: unknown[]): void; error(...args: unknown[]): void };
declare const console: typeof $console;

declare const $device: {
  name(): string;
  model(): string;
  systemVersion(): string;
  batteryLevel(): number;
  isCharging(): boolean;
};

declare const $file: { read(path: string): Promise<string>; write(path: string, content: string): Promise<boolean>; list(path: string): Promise<string[]> };
declare const $system: Record<string, unknown>;
declare const $health: Record<string, unknown>;
declare const $location: Record<string, unknown>;
declare const $storage: { get(key: string): Promise<string | null>; set(key: string, value: string): Promise<void>; remove(key: string): Promise<void>; clear(): Promise<void> };
declare const $getenv: { get(key: string): string | undefined };
declare function $import(path: string): Promise<unknown>;
declare function $render(element: unknown): void;
declare const $dynamic_island: Record<string, unknown>;
declare const $element: { createElement(tag: unknown, props?: unknown, ...children: unknown[]): unknown };
declare const $component: Record<string, unknown>;
declare const $error: Record<string, unknown>;

declare namespace JSWidget {
  function createElement(tag: unknown, props?: unknown, ...children: unknown[]): unknown;
  const Fragment: string;
  namespace JSX {
    interface IntrinsicElements {
      /** hstack */
      hstack: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;
      /** 垂直对齐 */
      alignment?: "top" | "bottom" | "center" | "firstTextBaseline" | "lastTextBaseline";
      /** 水平间距 */
      spacing?: string | number | boolean;
      };
      /** vstack */
      vstack: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;
      /** 水平对齐 */
      alignment?: "leading" | "trailing" | "center";
      /** 垂直间距 */
      spacing?: string | number | boolean;
      };
      /** zstack */
      zstack: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;

      };
      /** hgrid */
      hgrid: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;
      /** 行数 */
      rows?: string | number | boolean;
      /** 列配置 JSON 字符串 */
      columns?: string | number | boolean;
      /** 间距 */
      spacing?: string | number | boolean;
      };
      /** vgrid */
      vgrid: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;
      /** 行配置 JSON 字符串 */
      rows?: string | number | boolean;
      /** 列数 */
      columns?: string | number | boolean;
      /** 间距 */
      spacing?: string | number | boolean;
      };
      /** text */
      text: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;
      /** 字体大小 */
      font?: string | number | boolean;
      /** 粗体 */
      bold?: string | number | boolean;
      /** 斜体 */
      italic?: string | number | boolean;
      /** 文字颜色 */
      color?: string | number | boolean;
      /** 行数限制 */
      lineLimit?: string | number | boolean;
      /** 最小缩放 */
      minimumScaleFactor?: string | number | boolean;
      };
      /** date */
      date: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;
      /** 日期格式 */
      format?: string | number | boolean;
      /** 显示样式 */
      style?: "date" | "time" | "relative";
      };
      /** image */
      image: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;
      /** bundle 内图片名 */
      name?: string | number | boolean;
      /** 网络 URL */
      url?: string | number | boolean;
      /** 可拉伸 */
      resizable?: string | number | boolean;
      /** 适应 */
      scaledToFit?: string | number | boolean;
      /** 填充 */
      scaledToFill?: string | number | boolean;
      };
      /** gif */
      gif: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;
      /** GIF 资源名 */
      name?: string | number | boolean;
      };
      /** spacer */
      spacer: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;
      /** 最小长度 */
      minLength?: string | number | boolean;
      /** 最大长度 */
      maxLength?: string | number | boolean;
      };
      /** rect */
      rect: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;

      };
      /** capsule */
      capsule: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;

      };
      /** ellipse */
      ellipse: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;

      };
      /** circle */
      circle: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;

      };
      /** gauge */
      gauge: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;
      /** 当前值 */
      value?: string | number | boolean;
      /** 最小值 */
      min?: string | number | boolean;
      /** 最大值 */
      max?: string | number | boolean;
      };
      /** chart */
      chart: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;
      /** 图表数据 JSON */
      data?: string | number | boolean;
      /** 图表类型 */
      type?: "line" | "bar" | "pie";
      };
      /** link */
      link: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;
      /** 链接地址 */
      url?: string | number | boolean;
      /** 目标 */
      destination?: string | number | boolean;
      };
      /** divider */
      divider: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;

      };
      /** line */
      line: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;

      };
      /** roundedrect */
      roundedrect: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;
      /** 圆角半径 */
      cornerRadius?: string | number | boolean;
      };
      /** icon */
      icon: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;
      /** SF Symbol 名 */
      name?: string | number | boolean;
      /** 尺寸 */
      size?: string | number | boolean;
      };
      /** label */
      label: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;

      };
      /** progress */
      progress: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;
      /** 0-1 进度 */
      value?: string | number | boolean;
      };
      /** ring */
      ring: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;

      };
      /** badge */
      badge: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;

      };
      /** chip */
      chip: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;

      };
      /** stat */
      stat: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;

      };
      /** button */
      button: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;
      /** 点击动作名 */
      action?: string | number | boolean;
      /** 按钮样式 */
      style?: string | number | boolean;
      };
      /** toggle */
      toggle: {
      frame?: string;
      padding?: number | string;
      backgroundColor?: string;
      foregroundColor?: string;
      cornerRadius?: number;
      opacity?: number;
      rotationEffect?: number;
      scaleEffect?: number;
      offset?: string;
      shadow?: string;
      blur?: number;
      animation?: string;
      /** 是否开启 */
      isOn?: string | number | boolean;
      /** 切换回调名 */
      action?: string | number | boolean;
      };
    }
  }
}
